### ISSUE TITLE
This library is very similar to MobX. It feels like a lighter version of MobX

### ISSUE THREAD

**Issue by kyungjoongo2** [RisingStack/react-easy-state#125]
This library is very similar to MobX.
It feels like a lighter version of MobX.
Much better than complex redux state management,
What do you think?

**Comment by nitelite** [comment]
Yeah, the exact reason why I enjoy using it. I have switched to [react-osh](https://www.npmjs.com/package/react-osh) lately though since updates to this project seem to have at least stopped for a while. react-osh also fixed one of my bugs when trying to keep the cursor position inside the value in text fields when updating the value with new keypresses.

**Comment by rolandszoke** [comment]
The fix for the cursor position bug is coming in the next release :relaxed:

**Comment by solkimicreb** [comment]
The lib is moved to `@risingstack/react-easy-state` (starting from the latest v6.2.0) without breaking changes. Please move to the new repo for the cursor positioning fix (and some other goodies) 🙂
