### ISSUE TITLE
Top down rendering?

### ISSUE THREAD

**Issue by joelmoss** [RisingStack/react-easy-state#166]
So react-redux has a few performance optimisations built in, that I believe are important. The main one being that components are updated in a top down manner. So if parent and child components are subscribed to the same state, and that state changes, react-redux will make sure the parent component re-renders before the child.

How does react-easy-state handle this?

**Comment by solkimicreb** [comment]
This is covered with tests [here](https://github.com/RisingStack/react-easy-state/blob/master/__tests__/edgeCases.test.jsx#L186). I have to admit that there might be edge cases that the test does not cover though and I have to rethink how exactly we handle this (it is partially handled by the guarantees from the underlying library). I will look a bit into this again to refresh my memories 🙂

**Comment by joelmoss** [comment]
Nice! thx.

**Comment by solkimicreb** [comment]
@joelmoss Sooo... it turned out the tests I linked were false negatives (because of the usage of [React DOM's act](https://reactjs.org/docs/test-utils.html#act)) and we re-introduced the zombie child issue in v6.2.0. A bit embarrassing 😄 

I released **v6.3.0** which corrected the tests and fixed the zombie child issue (by using React `unstable_batchedUpdates`) again. Please update to that version to save yourself some headaches. Thanks!

**Comment by joelmoss** [comment]
Testing is hard 😏
