### ISSUE TITLE
Stores inside Store get undefined !

### ISSUE THREAD

**Issue by jonlepage** [RisingStack/react-easy-state#182]
**React Easy State version:** 6.3.0
**Platform:** nwjs,node win x64

**Describe the bug**
If we ref stores inside store, they are undefined.
I need a store that's can handle all projet stores.

---

### For tougher bugs

**To Reproduce**
I made you small example
SEE LINE: `27 & 29`
https://codesandbox.io/s/stores-handle-store-qb4cb?file=/src/App.jsx
If you expand the `#1` you can see the bug
If you expand `#2`, all work fine. (without store)

**Expected behavior**
We should able serialise a store from store.
Also this allow add store as plugins for a app.

---

thanks a lot for help and tips.

**Comment by jonlepage** [comment]
**edit**: i found i little workaround that's seem work.
We need use getter here.
```js
export const Store_Global = store({
  STORES: {
    //CORE: { Store_1, Store_2, Store_3 }, // not Work
    get CORE() { return { Store_1, Store_2, Store_3 }; }, // work
  }
});
```
The only issue is this create a new Objets for every access.

**Comment by solkimicreb** [comment]
Hi! Thanks for the codesandbox repro!

I think this is not related to RES. The issue is caused by a circular dependency (index.js -> App.js -> index.js). The bundler tries its best to resolve it but it can't do it for things defined at the global or module scope (which are executed right away). See this [slightly modified repro](https://codesandbox.io/s/stores-handle-store-so9go?file=/src/App.jsx) with the `store` wrappers removed.

Try to move `store1` and `store2` out of the `index.js` file and into a separate `stores.js` file maybe. That should fix it.
