### ISSUE TITLE
React hooks dependencies and react-easy-state

### ISSUE THREAD

**Issue by Hurtak** [RisingStack/react-easy-state#91]
Hi,

currently when you use global state values from react-easy-state in hook dependencies, it produces warning.

```jsx
import React, { useEffect } from "react";
import { store, view } from "react-easy-state";

const state = store({
  value: 1
})

const Component = view(() => {
  useEffect(() => {
    console.log(state.value)
  }, [state.value]);

  return <div>{state.value}</div>
})
```

`React Hook useEffect has unnecessary dependencies: 'state.value'. Either exclude them or remove the dependency array. Outer scope values like 'state.value' aren't valid dependencies because mutating them doesn't re-render the component  react-hooks/exhaustive-deps`

I think this is good time to reopen some ticket that I read earlier about introducing hooks api to solve this problem and have more unified interface.

eg instead of 
```js
const Component = view(() => {
  return <div>{state.value}</div>
})
```

to have

```js
const Component = () => {
  const {value} = useStore(state);
  return <div>{value}</div>
}
```

**Comment by solkimicreb** [comment]
Looks like a valid concern, I will look into it in the afternoon.

**Comment by solkimicreb** [comment]
I think this is only an issue for `useEffect`. Please check the new [`autoEffect` function](https://github.com/RisingStack/react-easy-state#adding-side-effects) for this use case (in the newly released @risingstack/react-easy-state v6.2.0).

**Comment by andreasgruenh** [comment]
What about dependencies for useCallback/useMemo?
The base problem is, that react-easy-state is always mutating the state object. This means, all referential equality checks will match (even if data changed). This become a problem as soon as you need to call into any code that is not built around react-easy-state

**Comment by solkimicreb** [comment]
Referential equality checks will match but it won't cause an issue. Callbacks won't have to be recreated since they will see the latest data without recreation (because the data is stored in mutable objects instead of closures). I really don't like hooks, I think they confuse even the smartest programmers.

We will take a pretty bold approach regarding hooks and try to get rid of their reliance on closures instead of doing a traditional integration. If everything goes right a new blog post will be released tomorrow [here](https://blog.risingstack.com/) that explains the broad idea and it will be followed by an 'Idiomatic React Easy State' docs that explain the edge cases soon.

The current hook integration situation is a mess but I think we can clean it up with zero API changes and some new patterns and docs.

**Comment by andreasgruenh** [comment]
Wow this sounds really interesting! Looking forward to the blog post!

One very simple example would be a library component, that implements pure component. Passend state objects will not trigger a rerender k side of this component, because the identity didn't change. Same with a library component that uses useEffect. The effect will not rerun, when the state object is mutated.

**Comment by solkimicreb** [comment]
> Passend state objects will not trigger a rerender k side of this component, because the identity didn't change.

I would argue with this. This is why we suggest people to wrap **ALL** components with `view` - even pure ones. If you wrap pure components they will re-render when the passed down store parts get mutated (they don't have to change by reference). The same stands for useEffect (if I understood correctly). 

There are pretty bad known edge cases though which have to be addressed. You are right about that.

**Comment by solkimicreb** [comment]
I think I finally got what you meant (:

I guess you mean the case when you don't have control over the mentioned pure component and can not wrap it with view (it's a third party component). There is a "Passing nested data to third party components." part in the docs that deals with this case, it is pretty rough though. We could make a more sophisticated helper for this in the future.

**Comment by andreasgruenh** [comment]
Thanks a lot for your patient responses! I really appreciate it.

**Comment by solkimicreb** [comment]
No worries, you are raising very valid issues.
