### ISSUE TITLE
batching eventlistener breaks input editing with React 16.9

### ISSUE THREAD

**Issue by NaNdreas** [RisingStack/react-easy-state#92]
Hello,

We've upgraded to React 16.9 (from 16.8) and it breaks our controlled inputs because of something inside react-easy-state. It is fixed as soon as I remove the batching of eventlisteners here: https://github.com/solkimicreb/react-easy-state/blob/1aeb0ddbc386a36adc3758a12d740989e99655a6/src/scheduler.js#L87

**What breaks?**
- Write "Hello world" in an input
- Edit the input: Put your cursor right before "world", and try to add "dear". 

**Expected result**: "Hello dear world". 
**Actual result**: "Hello dworldear"

The cursor moves to the end of the input everytime you add a character. 

Here's how to recreate:

```js
import React, { Component } from 'react';
import { view } from 'react-easy-state';

class Input extends Component {
  constructor(props) {
    super(props);

    this.state = {
      value: '',
    };

    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(e) {
    this.setState({ value: e.target.value })
  }

  render() {
    return <input type="text" value={this.state.value} onChange={this.handleChange} />
  }
}

export default Input;
```

OR, with hooks:
```js
import React, { useState } from 'react';
import { view } from 'react-easy-state';

function Input() {
  const [value, setValue] = useState('');

  function handleChange(e) {
    setValue(e.target.value);
  }

  return <input type="text" value={value} onChange={handleChange} />
}

export default Input;
```

**Why is it related to react-easy-state?**

- Remove the line I mentioned above and it works
- Remove the react-easy-state import and it works
- Note that we're not even _using_ react-easy-state, only importing it. Same result if you do wrap the component in `view` though.

We noticed a comment a few lines above `// this should be removed when React's own batching is improved in the future`, perhaps React 16.9 batching is improved now? 😄 

Thanks for an otherwise great state management tool!

**Comment by silverwind** [comment]
Quite a critical bug imho. Repro at https://codesandbox.io/s/vigorous-grothendieck-63ybi.

Typing into the middle of `<input>` resets the cursors to the end. Is this module monkey-patching React given that the issue shows without wrapping a component in `view`? I would strongly suggest not doing that for forward compat cases like this.

**Comment by bkis** [comment]
Is or will this be fixed? I think it's quite a big usability flaw.

**Comment by luisherranz** [comment]
@solkimicreb I'd love to help with this but I'm going to need your help.

The first thing I wonder is if we can get rid of `unstable_batchedUpdates` altogether.

Is the monkey-patching of `scheduler.js` used to:
- Solve the stale-props/zombie-children* problem? If it is not, how does `react-easy-state` solve it?
- Batch mutations together (like the old mobx `transaction`)?
- Any other reason?

\* _There's an excellent article of Kai Hao (@kevin940726) about [the stale-props/zombie-children problem](https://kaihao.dev/posts/Stale-props-and-zombie-children-in-Redux) of state managers. Following that, Paul Henschel (@drcmda) introduced an alternative solution on [Zustand](https://github.com/react-spring/zustand) based on an incremental id which may be interesting: https://github.com/react-spring/zustand/pull/65_

**Comment by luisherranz** [comment]
The React dev team has released the documentation of React Concurrent. It states this about `unsafe_batchedUpdates`:

> *: Legacy mode has automatic batching in React-managed events but it’s limited to one browser task. Non-React events must opt-in using unstable_batchedUpdates. In Blocking Mode and Concurrent Mode, all setStates are batched by default.

https://reactjs.org/docs/concurrent-mode-adoption.html#feature-comparison

I've done some tests and it works great. It looks like `unsafe_batchedUpdates` is not needed at all in Concurrent mode:

https://codesandbox.io/s/react-easy-state-batch-bug-v5yne

_I had to do the tests in the DOM because the testing library of React has not been updated yet to support Concurrent mode._ 

It also works on the upcoming [Blocking mode](https://reactjs.org/docs/concurrent-mode-adoption.html#migration-step-blocking-mode), which could be adopted as soon as Concurrent mode is released:

> For older codebases, Concurrent Mode might be a step too far. This is why we also provide a new “Blocking Mode” in the experimental React builds. You can try it by substituting createRoot with createBlockingRoot. It only offers a small subset of the Concurrent Mode features, but it is closer to how React works today and can serve as a migration step.

I wonder how long would it take to the React team to release Concurrent mode in the stable version, tho.

So on the other hand, the way I was thinking to solve this is using an async scheduler. The library `@nx-js/queue-util` (by @solkimicreb as well) works fine.

This is the same codesandbox with tests but with React version 16.11. Without scheduler, but with the async scheduler fix. The`<Input>` component works fine again.

https://codesandbox.io/s/react-easy-state-batch-bug-async-scheduler-6q2dt

Miklos, what do you think? What is the advantage of monkey patching the native elements over using an async scheduler and why did you do that instead of this in the first place?

**Comment by ciaoben** [comment]
It seems that this project is not maintained anymore... Did you fork it @luisherranz ?

**Comment by luisherranz** [comment]
Yeah, we forked it, but only because we wanted to implement a different API (similar to Overmind) and add support for middleware (we're still working on that). Even tho [it works fine outside](https://codesandbox.io/s/frontityconnect-minimal-example-f7pw5) of our [Frontity framework](https://frontity.org), it's still meant to be used inside Frontity and we have no documentation apart from the general [Frontity Docs](https://docs.frontity.org/). By the way, I haven't fixed the bug either in our fork. I was waiting to get an official response from @solkimicreb. 

So, instead of forking this library, and taking into account that the problem will be solved once React Concurrent is released, how about using [`patch-package`](https://www.npmjs.com/package/patch-package) to get rid of the scheduler and modify the `view.js` file to work with `@nx-js/queue-util`, like in this [codesandbox](https://codesandbox.io/s/react-easy-state-batch-bug-async-scheduler-6q2dt)?

It also seems like [these guys have downgraded to v5](https://github.com/TeselaGen/openVectorEditor/commit/4c6116cf4b7da2a42eae8a3c1dece59b4ef1ef20) to get rid of the bug, although I don't know what other changes were introduced in the v6 version.

**Comment by solkimicreb** [comment]
The package is moved to [@risingstack/react-easy-state](https://www.npmjs.com/package/@risingstack/react-easy-state) v6.2.0 of the new package includes the fix for this issue, please move to that package 🙂 There are no breaking changes.
