### ISSUE TITLE
Question about rendering

### ISSUE THREAD

**Issue by siokstoksanoks** [RisingStack/react-easy-state#97]
Hi, why this library tries to manage rendering instead of managing only the state? 

For example redux manages only the state and nothing more. 

The view() should only pass the props to the components and thats it. 
Leave the rendering (and rerendering) for the default react behaviour. If it is a pure component it has own reconciliation by default, if it is a component leave the work for the componentShouldUpdate.

**Comment by ricardobeat** [comment]
@siokstoksanoks there is no way to re-render a component other than telling React to do it. This library does it by calling `setState()`: https://github.com/solkimicreb/react-easy-state/blob/master/src/view.js#L16-L17

**Comment by solkimicreb** [comment]
"State management" has a pretty broad and vague definition. As I understand you are missing the dependency injection part that most other libraries include. That's fairly easy to implement and we are already playing with a possible accompanying injector library instead of putting it into this lib. (Some people prefer to not use dependency injection in their code).

The library is comparable to 'mobx-react' and 'react-redux' instead of 'redux' and 'mobx'. The vanilla 'redux'/'mobx' like core is called [@nx-js/observer-util](https://github.com/nx-js/observer-util). Maybe that's what you are looking for.
